export interface Item {
  code: number;
  name: string;
}

export const stacks: Record<string, Item[]> = {
  "Holguras y niveles": [
    { code: 193, name: "Faro vs Parrilla" },
    { code: 622, name: "Faro vs facia" },
    { code: 621, name: "Parrilla vs Facia" },
    { code: 307, name: "Cofre vs Parrilla" },
    { code: 647, name: "Faro vs Cofre" },
    { code: 121, name: "Salpicadera vs cofre" },
    { code: 278, name: "Marco vs Toldo" },
    { code: 173, name: "Entre marcos" },
    { code: 409, name: "Tapa Gas" },
    { code: 638, name: "Salpicadera vs Pilar" },
    { code: 646, name: "Faro vs Salpicadera" },
    { code: 277, name: "Marco vs pilar" },
    { code: 543, name: "Calavera vs cosatado de caja" },
    { code: 333, name: "Puerta vs pilar" },
    { code: 174, name: "Entre puertas" },
    { code: 334, name: "Puerta vs salpicadera" },
  ],
  "Partes Interiores": [
    { code: 717, name: "Botones volante" },
    { code: 606, name: "Pad Volante" },
    { code: 464, name: "Volante" },
    { code: 295, name: "Odometro" },
    { code: 629, name: "Pantalla Meter" },
    { code: 450, name: "Velocimetro" },
    { code: 113, name: "SW ignicion" },
    { code: 349, name: "Respaldo Asiento" },
    { code: 92, name: "Candado cinturon seguridad" },
    { code: 628, name: "Porta vasos" },
    { code: 50, name: "Asiento" },
    { code: 779, name: "Sw calefactor asiento" },
    { code: 3, name: "Aire Acondicionado" },
    { code: 785, name: "Perilla 4WD" },
    { code: 207, name: "Freno de mano" },
    { code: 451, name: "Ventilas Tablero" },
    { code: 235, name: "SW intermitentes" },
    { code: 630, name: "Pantalla" },
    { code: 669, name: "Toma corriente tablero" },
    { code: 672, name: "Jack Audio" },
    { code: 315, name: "Perilla Palanca Velocidades" },
    { code: 303, name: "Palanca velocidades TM" },
    { code: 304, name: "Palanca velocidades TA" },
    { code: 152, name: "Cubierta palanca velocidades" },
  ],
  "Partes exteriores": [
    { code: 185, name: "Esquinero Puerta" },
    { code: 138, name: "Cristal Puerta" },
    { code: 175, name: "Espejo lateral" },
    { code: 98, name: "Cañuela marco" },
    { code: 286, name: "Moldura parabrisas" },
    { code: 305, name: "Parabrisas" },
    { code: 342, name: "Rejilla parabrisas" },
    { code: 542, name: "Esquinero rejilla parabrisas" },
    { code: 403, name: "Cofre" },
    { code: 165, name: "Direccional" },
    { code: 191, name: "Faro" },
    { code: 306, name: "Parrilla" },
    { code: 170, name: "Emblema nissan" },
    { code: 189, name: "Faldon" },
    { code: 641, name: "Bisel faro" },
    { code: 490, name: "Faro niebla" },
    { code: 155, name: "Facia" },
    { code: 242, name: "LLanta" },
    { code: 354, name: "Rin" },
    { code: 225, name: "Guardafango" },
    { code: 659, name: "Escalon estribo" },
    { code: 186, name: "Estribo" },
    { code: 332, name: "Puerta" },
    { code: 246, name: "Lodera" },
    { code: 275, name: "Manija puerta" },
    { code: 317, name: "Pilar" },
    { code: 135, name: "Costado de caja" },
    { code: 481, name: "Cintilla" },
    { code: 194, name: "Filillo" },
    { code: 279, name: "Marco puerta" },
    { code: 358, name: "Salpicadera" },
  ],
  Pilares: [
    { code: 54, name: "BODY-NS" },
    { code: 55, name: "BODY-CDS" },
    { code: 56, name: "BODY-F&F" },
    { code: 57, name: "BODY-ATE" },
    { code: 58, name: "BODY-OC" },
    { code: 59, name: "BODY-HAR" },
    { code: 60, name: "BODY-S&R." },
    { code: 61, name: "BODY-SHW" },
    { code: 62, name: "C-4-NS" },
    { code: 63, name: "C-4-CDS" },
    { code: 64, name: "C-4-F&F" },
    { code: 65, name: "C-4-ATE" },
    { code: 66, name: "C-4-OC" },
    { code: 67, name: "C-4-HAR" },
    { code: 68, name: "C-4-S&R." },
    { code: 69, name: "C-4-SHW" },
    { code: 70, name: "PAINT-NS" },
    { code: 71, name: "PAINT-CDS" },
    { code: 72, name: "PAINT-F&F" },
    { code: 73, name: "PAINT-ATE" },
    { code: 74, name: "PAINT-OC" },
    { code: 75, name: "PAINT-HAR" },
    { code: 76, name: "PAINT-S&R." },
    { code: 77, name: "PAINT-SHW" },
    { code: 78, name: "C-3-NS" },
    { code: 79, name: "C-3-CDS" },
    { code: 80, name: "C-3-F&F" },
    { code: 81, name: "C-3-ATE" },
    { code: 82, name: "C-3-OC" },
    { code: 83, name: "C-3-HAR" },
    { code: 84, name: "C-3-S&R." },
    { code: 85, name: "C-3-SHW" },
    { code: 86, name: "TRIM-NS" },
    { code: 87, name: "TRIM-CDS" },
    { code: 88, name: "TRIM-F&F" },
    { code: 89, name: "TRIM-ATE" },
    { code: 90, name: "TRIM-OC" },
    { code: 91, name: "TRIM-HAR" },
    { code: 92, name: "TRIM-S&R." },
    { code: 93, name: "TRIM-SHW" },
    { code: 94, name: "CHASSIS-NS" },
    { code: 95, name: "CHASSIS-CDS" },
    { code: 96, name: "CHASSIS-F&F" },
    { code: 97, name: "CHASSIS-ATE" },
    { code: 98, name: "CHASSIS-OC" },
    { code: 99, name: "CHASSIS-HAR" },
    { code: 100, name: "CHASSIS-S&R." },
    { code: 101, name: "CHASSIS-SHW" },
    { code: 102, name: "L.F.-NS" },
    { code: 103, name: "L.F.-CDS" },
    { code: 104, name: "L.F.-F&F" },
    { code: 105, name: "L.F.-ATE" },
    { code: 106, name: "L.F.-OC" },
    { code: 107, name: "L.F.-HAR" },
    { code: 108, name: "L.F.-S&R." },
    { code: 109, name: "L.F.-SHW" },
    { code: 110, name: "PQE-NS" },
    { code: 111, name: "PQE-CDS" },
    { code: 112, name: "PQE-F&F" },
    { code: 113, name: "PQE-ATE" },
    { code: 114, name: "PQE-OC" },
    { code: 115, name: "PQE-HAR" },
    { code: 116, name: "PQE-S&R." },
    { code: 117, name: "PQE-SHW" },
    { code: 118, name: "IP-NS" },
    { code: 119, name: "IP-CDS" },
    { code: 120, name: "IP-F&F" },
    { code: 121, name: "IP-ATE" },
    { code: 122, name: "IP-OC" },
    { code: 123, name: "IP-HAR" },
    { code: 124, name: "IP-S&R." },
    { code: 125, name: "IP-SHW" },
    { code: 126, name: "STAMPPING-NS" },
    { code: 127, name: "STAMPPING-CDS" },
    { code: 128, name: "STAMPPING-F&F" },
    { code: 129, name: "STAMPPING-ATE" },
    { code: 130, name: "STAMPPING-OC" },
    { code: 131, name: "STAMPPING-HAR" },
    { code: 132, name: "STAMPPING-S&R." },
    { code: 133, name: "STAMPPING-SHW" },
  ],
  "Lugar": [
    { code: 0, name: "Sin Lugar" },
  { code: 1, name: "CENTRAL" },
  { code: 2, name: "CENTRAL DERECHO" },
  { code: 3, name: "CENTRAL IZQUIERDO" },
  { code: 4, name: "DELANTERO" },
  { code: 5, name: "DELANTERO DERECHO" },
  { code: 6, name: "DELANTERO DERECHO INTERIOR" },
  { code: 7, name: "DELANTERO IZQUIERDO" },
  { code: 8, name: "DELANTERO IZQUIERDO INFERIOR" },
  { code: 9, name: "DELANTERO IZQUIERDO INTERIOR" },
  { code: 10, name: "DELANTERO IZQUIERDO SUPERIOR" },
  { code: 11, name: "EN GENERAL" },
  { code: 12, name: "EXTERIOR" },
  { code: 13, name: "INFERIOR" },
  { code: 14, name: "INFERIOR DERECHO" },
  { code: 15, name: "INFERIOR IZQUIERDO" },
  { code: 16, name: "INTERIOR" },
  { code: 17, name: "INTERIOR CENTRAL DERECHO" },
  { code: 18, name: "INTERIOR CENTRAL IZQUIERDO" },
  { code: 19, name: "INTERIOR DERECHO" },
  { code: 20, name: "INTERIOR IZQUIERDO" },
  { code: 21, name: "LADO DERECHO" },
  { code: 22, name: "LADO IZQUIERDO" },
  { code: 23, name: "LATERALES" },
  { code: 24, name: "LUGAR UNICO" },
  { code: 25, name: "SUPERIOR" },
  { code: 26, name: "SUPERIOR DERECHO" },
  { code: 27, name: "SUPERIOR IZQUIERDO" },
  { code: 28, name: "TRASERO" },
  { code: 29, name: "TRASERO DERECHO" },
  { code: 30, name: "TRASERO DERECHO INFERIOR" },
  { code: 31, name: "TRASERO DERECHO INTERIOR" },
  { code: 32, name: "TRASERO DERECHO SUPERIOR" },
  { code: 33, name: "TRASERO IZQUIERDO" },
  { code: 34, name: "TRASERO IZQUIERDO INFERIOR" },
  { code: 35, name: "TRASERO IZQUIERDO INTERIOR" },
  { code: 36, name: "TRASERO IZQUIERDO SUPERIOR" },
  { code: 37, name: "BAJO PISO" },
  { code: 38, name: "A DUCTO DE AIRE" },
  { code: 39, name: "A CANISTER" },
  { code: 40, name: "A MOTOR" },
  { code: 41, name: "DELANTERO DERECHO SUPERIOR" },
  { code: 42, name: "A FILTRO DE AIRE" },
  { code: 43, name: "A COLECTOR" },
  { code: 44, name: "CENTRAL DERECHO SUPERIOR" },
  { code: 45, name: "CENTRAL IZQUIERDO SUPERIOR" },
  { code: 46, name: "DELANTERO DERECHO INFERIOR" },
  { code: 47, name: "A CORAZA" },
  { code: 48, name: "A CAJA DE AIRE" },
  { code: 49, name: "A CHASIS" },
  { code: 50, name: "A EJE" },
  { code: 51, name: "A TRANSMISION" },
  { code: 52, name: "A CILINDRO FRENOS" },
  { code: 53, name: "A CILINDRO CLUTCH" }
  ]
};
