export interface Item {
  code: number;
  name: string;
}

export const stacks: Record<string, Item[]> = {
  "Holguras y niveles": [
    { code: 193, name: "Faro vs Parrilla" },
    { code: 622, name: "Faro vs facia" },
    { code: 621, name: "Parrilla vs Facia" },
    { code: 307, name: "Cofre vs Parrilla" },
    { code: 647, name: "Faro vs Cofre" },
    { code: 121, name: "Salpicadera vs cofre" },
    { code: 278, name: "Marco vs Toldo" },
    { code: 173, name: "Entre marcos" },
    { code: 409, name: "Tapa Gas" },
    { code: 638, name: "Salpicadera vs Pilar" },
    { code: 646, name: "Faro vs Salpicadera" },
    { code: 277, name: "Marco vs pilar" },
    { code: 543, name: "Calavera vs cosatado de caja" },
    { code: 333, name: "Puerta vs pilar" },
    { code: 174, name: "Entre puertas" },
    { code: 334, name: "Puerta vs salpicadera" },
  ],
  "Partes Interiores": [
    { code: 717, name: "Botones volante" },
    { code: 606, name: "Pad Volante" },
    { code: 464, name: "Volante" },
    { code: 295, name: "Odometro" },
    { code: 629, name: "Pantalla Meter" },
    { code: 450, name: "Velocimetro" },
    { code: 113, name: "SW ignicion" },
    { code: 349, name: "Respaldo Asiento" },
    { code: 92, name: "Candado cinturon seguridad" },
    { code: 628, name: "Porta vasos" },
    { code: 50, name: "Asiento" },
    { code: 779, name: "Sw calefactor asiento" },
    { code: 3, name: "Aire Acondicionado" },
    { code: 785, name: "Perilla 4WD" },
    { code: 207, name: "Freno de mano" },
    { code: 451, name: "Ventilas Tablero" },
    { code: 235, name: "SW intermitentes" },
    { code: 630, name: "Pantalla" },
    { code: 669, name: "Toma corriente tablero" },
    { code: 672, name: "Jack Audio" },
    { code: 315, name: "Perilla Palanca Velocidades" },
    { code: 303, name: "Palanca velocidades TM" },
    { code: 304, name: "Palanca velocidades TA" },
    { code: 152, name: "Cubierta palanca velocidades" },
  ],
  "Partes exteriores": [
    { code: 185, name: "Esquinero Puerta" },
    { code: 138, name: "Cristal Puerta" },
    { code: 175, name: "Espejo lateral" },
    { code: 98, name: "Cañuela marco" },
    { code: 286, name: "Moldura parabrisas" },
    { code: 305, name: "Parabrisas" },
    { code: 342, name: "Rejilla parabrisas" },
    { code: 542, name: "Esquinero rejilla parabrisas" },
    { code: 403, name: "Cofre" },
    { code: 165, name: "Direccional" },
    { code: 191, name: "Faro" },
    { code: 306, name: "Parrilla" },
    { code: 170, name: "Emblema nissan" },
    { code: 189, name: "Faldon" },
    { code: 641, name: "Bisel faro" },
    { code: 490, name: "Faro niebla" },
    { code: 155, name: "Facia" },
    { code: 242, name: "LLanta" },
    { code: 354, name: "Rin" },
    { code: 225, name: "Guardafango" },
    { code: 659, name: "Escalon estribo" },
    { code: 186, name: "Estribo" },
    { code: 332, name: "Puerta" },
    { code: 246, name: "Lodera" },
    { code: 275, name: "Manija puerta" },
    { code: 317, name: "Pilar" },
    { code: 135, name: "Costado de caja" },
    { code: 481, name: "Cintilla" },
    { code: 194, name: "Filillo" },
    { code: 279, name: "Marco puerta" },
    { code: 358, name: "Salpicadera" },
  ],
  Pilares: [
    { code: 54, name: "BODY-NS" },
    { code: 55, name: "BODY-CDS" },
    { code: 56, name: "BODY-F&F" },
    { code: 57, name: "BODY-ATE" },
    { code: 58, name: "BODY-OC" },
    { code: 59, name: "BODY-HAR" },
    { code: 60, name: "BODY-S&R." },
    { code: 61, name: "BODY-SHW" },
    { code: 62, name: "C-4-NS" },
    { code: 63, name: "C-4-CDS" },
    { code: 64, name: "C-4-F&F" },
    { code: 65, name: "C-4-ATE" },
    { code: 66, name: "C-4-OC" },
    { code: 67, name: "C-4-HAR" },
    { code: 68, name: "C-4-S&R." },
    { code: 69, name: "C-4-SHW" },
    { code: 70, name: "PAINT-NS" },
    { code: 71, name: "PAINT-CDS" },
    { code: 72, name: "PAINT-F&F" },
    { code: 73, name: "PAINT-ATE" },
    { code: 74, name: "PAINT-OC" },
    { code: 75, name: "PAINT-HAR" },
    { code: 76, name: "PAINT-S&R." },
    { code: 77, name: "PAINT-SHW" },
    { code: 78, name: "C-3-NS" },
    { code: 79, name: "C-3-CDS" },
    { code: 80, name: "C-3-F&F" },
    { code: 81, name: "C-3-ATE" },
    { code: 82, name: "C-3-OC" },
    { code: 83, name: "C-3-HAR" },
    { code: 84, name: "C-3-S&R." },
    { code: 85, name: "C-3-SHW" },
    { code: 86, name: "TRIM-NS" },
    { code: 87, name: "TRIM-CDS" },
    { code: 88, name: "TRIM-F&F" },
    { code: 89, name: "TRIM-ATE" },
    { code: 90, name: "TRIM-OC" },
    { code: 91, name: "TRIM-HAR" },
    { code: 92, name: "TRIM-S&R." },
    { code: 93, name: "TRIM-SHW" },
    { code: 94, name: "CHASSIS-NS" },
    { code: 95, name: "CHASSIS-CDS" },
    { code: 96, name: "CHASSIS-F&F" },
    { code: 97, name: "CHASSIS-ATE" },
    { code: 98, name: "CHASSIS-OC" },
    { code: 99, name: "CHASSIS-HAR" },
    { code: 100, name: "CHASSIS-S&R." },
    { code: 101, name: "CHASSIS-SHW" },
    { code: 102, name: "L.F.-NS" },
    { code: 103, name: "L.F.-CDS" },
    { code: 104, name: "L.F.-F&F" },
    { code: 105, name: "L.F.-ATE" },
    { code: 106, name: "L.F.-OC" },
    { code: 107, name: "L.F.-HAR" },
    { code: 108, name: "L.F.-S&R." },
    { code: 109, name: "L.F.-SHW" },
    { code: 110, name: "PQE-NS" },
    { code: 111, name: "PQE-CDS" },
    { code: 112, name: "PQE-F&F" },
    { code: 113, name: "PQE-ATE" },
    { code: 114, name: "PQE-OC" },
    { code: 115, name: "PQE-HAR" },
    { code: 116, name: "PQE-S&R." },
    { code: 117, name: "PQE-SHW" },
    { code: 118, name: "IP-NS" },
    { code: 119, name: "IP-CDS" },
    { code: 120, name: "IP-F&F" },
    { code: 121, name: "IP-ATE" },
    { code: 122, name: "IP-OC" },
    { code: 123, name: "IP-HAR" },
    { code: 124, name: "IP-S&R." },
    { code: 125, name: "IP-SHW" },
    { code: 126, name: "STAMPPING-NS" },
    { code: 127, name: "STAMPPING-CDS" },
    { code: 128, name: "STAMPPING-F&F" },
    { code: 129, name: "STAMPPING-ATE" },
    { code: 130, name: "STAMPPING-OC" },
    { code: 131, name: "STAMPPING-HAR" },
    { code: 132, name: "STAMPPING-S&R." },
    { code: 133, name: "STAMPPING-SHW" },
  ],
  "Lugar": [
    { code: 0, name: "Sin Lugar" },
  { code: 1, name: "CENTRAL" },
  { code: 2, name: "CENTRAL DERECHO" },
  { code: 3, name: "CENTRAL IZQUIERDO" },
  { code: 4, name: "DELANTERO" },
  { code: 5, name: "DELANTERO DERECHO" },
  { code: 6, name: "DELANTERO DERECHO INTERIOR" },
  { code: 7, name: "DELANTERO IZQUIERDO" },
  { code: 8, name: "DELANTERO IZQUIERDO INFERIOR" },
  { code: 9, name: "DELANTERO IZQUIERDO INTERIOR" },
  { code: 10, name: "DELANTERO IZQUIERDO SUPERIOR" },
  { code: 11, name: "EN GENERAL" },
  { code: 12, name: "EXTERIOR" },
  { code: 13, name: "INFERIOR" },
  { code: 14, name: "INFERIOR DERECHO" },
  { code: 15, name: "INFERIOR IZQUIERDO" },
  { code: 16, name: "INTERIOR" },
  { code: 17, name: "INTERIOR CENTRAL DERECHO" },
  { code: 18, name: "INTERIOR CENTRAL IZQUIERDO" },
  { code: 19, name: "INTERIOR DERECHO" },
  { code: 20, name: "INTERIOR IZQUIERDO" },
  { code: 21, name: "LADO DERECHO" },
  { code: 22, name: "LADO IZQUIERDO" },
  { code: 23, name: "LATERALES" },
  { code: 24, name: "LUGAR UNICO" },
  { code: 25, name: "SUPERIOR" },
  { code: 26, name: "SUPERIOR DERECHO" },
  { code: 27, name: "SUPERIOR IZQUIERDO" },
  { code: 28, name: "TRASERO" },
  { code: 29, name: "TRASERO DERECHO" },
  { code: 30, name: "TRASERO DERECHO INFERIOR" },
  { code: 31, name: "TRASERO DERECHO INTERIOR" },
  { code: 32, name: "TRASERO DERECHO SUPERIOR" },
  { code: 33, name: "TRASERO IZQUIERDO" },
  { code: 34, name: "TRASERO IZQUIERDO INFERIOR" },
  { code: 35, name: "TRASERO IZQUIERDO INTERIOR" },
  { code: 36, name: "TRASERO IZQUIERDO SUPERIOR" },
  { code: 37, name: "BAJO PISO" },
  { code: 38, name: "A DUCTO DE AIRE" },
  { code: 39, name: "A CANISTER" },
  { code: 40, name: "A MOTOR" },
  { code: 41, name: "DELANTERO DERECHO SUPERIOR" },
  { code: 42, name: "A FILTRO DE AIRE" },
  { code: 43, name: "A COLECTOR" },
  { code: 44, name: "CENTRAL DERECHO SUPERIOR" },
  { code: 45, name: "CENTRAL IZQUIERDO SUPERIOR" },
  { code: 46, name: "DELANTERO DERECHO INFERIOR" },
  { code: 47, name: "A CORAZA" },
  { code: 48, name: "A CAJA DE AIRE" },
  { code: 49, name: "A CHASIS" },
  { code: 50, name: "A EJE" },
  { code: 51, name: "A TRANSMISION" },
  { code: 52, name: "A CILINDRO FRENOS" },
  { code: 53, name: "A CILINDRO CLUTCH" }
  ],
  "defectos off": [
    { code: 6, name: "CARPET FLOOR - ALFOMBRA CABINA" },
  { code: 12, name: "WHEEL HOUSE OUT SIDE - ALOJAMIENTO RUEDA" },
  { code: 14, name: "SASH DOOR HOUSE - ALOJAMIENTO MARCO" },
  { code: 15, name: "GLASS FRONT WINDOW HOUSE - ALOJAMIENTO PARABRISAS" },
  { code: 16, name: "DOOR HOUSE - ALOJAMIENTO PUERTA" },
  { code: 31, name: "HARNESS SPEAKER - ARNES BOCINA RADIO" },
  { code: 37, name: "HARNESS DOOR - ARNES INT. DE PTA." },
  { code: 40, name: "HARNESS ENGINE - ARNES MOTOR" },
  { code: 44, name: "HARNESS MAIN - ARNES PRINCIPAL" },
  { code: 47, name: "HARNESS NEGATIVE - ARNES TIERRA" },
  { code: 49, name: "HANDLE PULL - ASIDERA" },
  { code: 50, name: "SEAT - ASIENTO" },
  { code: 61, name: "BATTERY - BATERIA" },
  { code: 66, name: "SPEAKER - BOCINA RADIO" },
  { code: 77, name: "BODY RR - CAJA" },
  { code: 78, name: "AIR BOX - CAJA AIRE" },
  { code: 80, name: "RELAYS BOX - CAJA RELAYS" },
  { code: 98, name: "GLASS RUN RUBBER DOOR - CAÑUELA MARCO" },
  { code: 105, name: "CHECK-LINK - CHECK-LINK" },
  { code: 109, name: "CABLE HOOD - CHICOTE COFRE" },
  { code: 114, name: "CYLINDER DOOR - CILINDRO PUERTA" },
  { code: 115, name: "CYLINDER GLOVE BOX - CILINDRO TAPA GUANTERA" },
  { code: 118, name: "SEAT BELT - CINTURON SEGURIDAD" },
  { code: 130, name: "STRIKER DOOR LOCK - CONTRA PUERTA" },
  { code: 132, name: "DASH - CORAZA" },
  { code: 135, name: "BODY SIDE PANEL BOX - COSTADO CAJA" },
  { code: 138, name: "GLASS DOOR - CRISTAL PUERTA" },
  { code: 155, name: "BUMPER FR - DEFENSA DELANTERA" },
  { code: 156, name: "BUMPER RR - DEFENSA TRASERA" },
  { code: 163, name: "REAR AXEL - DIFERENCIAL" },
  { code: 175, name: "MIRROR DOOR - ESPEJO EXTERIOR" },
  { code: 184, name: "TAP SILENT - ESPONJA ANTIRUIDO" },
  { code: 185, name: "RR DOOR CORNER MOULDING - ESQUINERO PUERTA" },
  { code: 186, name: "BODY SILL - ESTRIBO" },
  { code: 191, name: "HEAD LAMP - FARO" },
  { code: 194, name: "MOLDG ASSY DOOR OUTSIDE - FILILLO PUERTA" },
  { code: 197, name: "BODY SILL EDGE - FILO ESTRIBO" },
  { code: 211, name: "JACK COMPLETE - GATO" },
  { code: 218, name: "SEALING RUBBER-HOOD - GOMA DEFLECTORA" },
  { code: 220, name: "WEATHER STRIP DOOR - GOMA SELLO PUERTA" },
  { code: 222, name: "RUBBER STOPPER DOOR - GOMA TOPE PUERTA" },
  { code: 227, name: "ARM - HORQUILLA" },
  { code: 234, name: "SWITCH WARN THEFT - INTERRUPTOR ALARMA" },
  { code: 236, name: "SW DOOR - INTERRUPTOR PUERTA" },
  { code: 237, name: "HANDLE PULL - JALADERA PUERTA" },
  { code: 238, name: "ROOM LAMP - LAMPARA CABINA" },
  { code: 246, name: "MUDGUARD SET - LODERA" },
  { code: 255, name: "HEATER HOSE - MANGUERA CALEFACTOR" },
  { code: 256, name: "FUEL HOSE - MANGUERA COMBUSTIBLE" },
  { code: 275, name: "HANDLE DOOR INSIDE - MANIJA PUERTA" },
  { code: 279, name: "SASH DOOR - MARCO PUERTA" },
  { code: 280, name: "MASTER VAC - MASTER VAC" },
  { code: 281, name: "GLASS BACK WINDOW - MEDALLON" },
  { code: 286, name: "MOULDING WINDSHIELD - MOLDURA PARABRISAS" },
  { code: 292, name: "RR SPRING - MUELLES" },
  { code: 305, name: "GLASS WINDSHIELD - PARABRISAS" },
  ], 
  "defectos oof 2": [
    { code: 309, name: "LEVER PEDAL - PEDAL ACELERADOR" },
  { code: 317, name: "PILLAR - PILAR" },
  { code: 319, name: "FLOOR BOX - PISO CAJA" },
  { code: 321, name: "PLATE MODEL - PLACA MODELO" },
  { code: 323, name: "ESCUTCHE ON-INSIDE HANDLE - PLAFON PUERTA" },
  { code: 332, name: "DOOR - PUERTA" },
  { code: 333, name: "DOOR Vs PILLAR - PUERTA CON PILAR" },
  { code: 339, name: "EXT FR SIDE MBR - REFUERZO PISO" },
  { code: 342, name: "COVER COWLTOP GRILLE - REJILLA" },
  { code: 350, name: "BACK ROOM - RESPALDO CABINA" },
  { code: 354, name: "RHIN TIRE - RHIN ACERO" },
  { code: 358, name: "FENDER - SALPICADERA" },
  { code: 372, name: "BRACKET SEAT BELT - SOPORTE CINTURON SEGURIDAD" },
  { code: 380, name: "BRACKET JACK - SOPORTE GATO" },
  { code: 381, name: "BRACKET ENGINE MTG - SOPORTE MOTOR" },
  { code: 386, name: "BRACKET PANEL INSTRUMENT - SOPORTE TABLERO" },
  { code: 391, name: "BRACKET POWER STEERING - SOPTE. DIRECCION HIDR." },
  { code: 396, name: "PANEL INSTRUMENT - TABLERO" },
  { code: 397, name: "PANEL INST Vs FIN PILLAR - TABLERO C/VISTA PILAR" },
  { code: 400, name: "FUEL TANK - TANQUE COMBUSTIBLE" },
  { code: 403, name: "HOOD - TAPA COFRE" },
  { code: 405, name: "HANDLE PULL FINISHER - TAPA ASIDERA" },
  { code: 407, name: "BOX GLOVE - TAPA GUANTERA" },
  { code: 409, name: "LID GAS FILLER - TAPA TOMA GAS" },
  { code: 418, name: "ROOF - TOLDO" },
  { code: 428, name: "PIPE FRONT COOLER - TUBERIA AIRE ACOND." },
  { code: 429, name: "TUBE FUEL - TUBERIA COMBUSTIBLE" },
  { code: 430, name: "TUBE CLUTCH - TUBERIA EMBRAGUE" },
  { code: 432, name: "BRAKE PIPING - TUBERIA FRENOS" },
  { code: 435, name: "TUBE FILLER FUEL TANK - TUBO LLENADO COMBUSTIBLE" },
  { code: 448, name: "ROD HOOD - VARILLA COFRE" },
  { code: 455, name: "SUNVISOR - VISERA" },
  { code: 458, name: "PLATE KICKING - VISTA ESTRIBO" },
  { code: 459, name: "GARNISH PILLAR - VISTA PILAR" },
  { code: 460, name: "FINISHER DOOR - VISTA PUERTA" },
  { code: 462, name: "FINISHER INSTRUMENT PANEL - VISTA TABLERO" },
  { code: 463, name: "WELT DOOR - VIVO PUERTA" },
  { code: 481, name: "SASH DOOR BLACK - MARCO NEGRO DE PUERTA" },
  { code: 510, name: "COVER RR GATE - CUBIERTA COMPUERTA (MET.)" },
  { code: 511, name: "FIN WHEEL HOUSE - CUBIERTA ALOJ. LLANTA" },
  { code: 542, name: "M.WS.CORNER LW Vs FENDER - ESQUINERO Vs SALPICADERA" },
  { code: 546, name: "CHASSIS - CHASSIS" },
  { code: 548, name: "INSUL HOOD - AISLANTE DE CALOR COFRE" },
  { code: 554, name: "AIR BAG - BOLSA DE AIRE" },
  { code: 574, name: "SHAFT HOMOCINETIC - FLECHA HOMOCINETICA" },
  { code: 598, name: "HEAD LINING ROOF - TOLDO PREFORMADO" },
  { code: 600, name: "TURBINE - TURBINA" },
  { code: 603, name: "COOLER UNIT - ENFRIADOR DE AIRE" },
  { code: 606, name: "STEERING PAD - PAD DE VOLANTE" },
  { code: 608, name: "SIDE TURN LAMP - DIRECCIONAL SALPICADERA" },
  { code: 611, name: "OVER FENDER - CANTONERA" },
  { code: 617, name: "BACK ROOM FINISHER - VISTA RESPALDO CABINA" },
  { code: 623, name: "CHIPING PROTECTOR BOX - CHIPING PROTECTOR DE CAJA" },
  { code: 625, name: "CHIPING PROTECTOR PILLAR - CHIPING PROTECTOR PILAR" },
  { code: 627, name: "COVER COWL TOP - ESQUINERO DE REJILLA" },
  { code: 640, name: "FINISHER DOOR LAMP - LAMPARA VISTA PUERTA" },
  { code: 642, name: "GLASS REAR WINDOW HOUSE - ALOJAMIENTO MEDALLON" },
  { code: 643, name: "HARNESS ABS - ARNES ABS" },
  { code: 648, name: "HOOK BOX RAIL - RIEL GANCHOS DE CAJA" },
  { code: 657, name: "ROOF BAR - BARRA DE TOLDO" },
  { code: 659, name: "SIDE STEP - ESCALON ESTRIBO" },
  { code: 694, name: "ADAS - ADAS" },
  { code: 695, name: "SEAT BELT ADJUSTER - AJUSTADOR CINTURON SEG." },
  { code: 700, name: "BRACKET INT. SALPICADERA - BRACKET INT. SALPICADERA" },
  { code: 702, name: "IPDM BOX - CAJA IPDM" },
  { code: 710, name: "CHIPPING REAR BUMPER - CHIPPING DE DEFENSA RR" },
  { code: 711, name: "CHIPPING DOOR - CHIPPING DE PUERTA" },
  { code: 740, name: "DEFLECTOR RUBBER BOX - GOMA DEFLECTORA DE CAJA" },
  { code: 755, name: "ROOF MOULDING - MOLDURA TOLDO" },
  { code: 761, name: "BOX BACKREST - RESPALDO CAJA" },
  { code: 765, name: "CAMSHAFT SENSOR - SENSOR ARBOL DE LEVAS" },
  { code: 769, name: "CRASH SENSOR FLOOR AIR/B - SENSOR CRASH AIR/B PISO" },
  { code: 770, name: "CRASH SENSOR DOOR AIR/B - SENSOR CRASH AIR/B PTA" },
  { code: 794, name: "ANTIFREEZE PIPE - TUBERIA ANTICONGELANTE" },
  { code: 801, name: "CABIN BACK VENTS - VENTILAS RESPALDO CABINA" },
  { code: 802, name: "REAR BUMPER TRIM - VISTA DEFENSA TRASERA" },
  { code: 807, name: "CABIN BACK INSULATION - INSUL RESPALDO CABINA" },
  { code: 811, name: "PRO4EX LABEL - ETIQUETA PRO4EX" },
  { code: 812, name: "EXHAUST PIPE SUPPORT - SOPORTE TUBO DE ESCAPE" },
  { code: 817, name: "MIRROR COVER - CUBIERTA DE ESPEJO" },
  { code: 821, name: "BUMPER HARNESS - ARNES DEFENSA" },
  { code: 823, name: "SOS BUTTON - BOTON S.O.S." }
  ],
  "defectos 1": [
    { "code": 1, "name": "ABOLLADA POR DAÑO" },
    { "code": 2, "name": "ABOLLADA POR PROCESO" },
    { "code": 3, "name": "ABOMBADA" },
    { "code": 5, "name": "ABRAZADERA FALTA APRIETE" },
    { "code": 6, "name": "ABRAZADERA MAL COLOCADA" },
    { "code": 11, "name": "ARNES SIN SUJETAR" },
    { "code": 12, "name": "ARRUGADO" },
    { "code": 14, "name": "BARNIZ ESCURRIDO" },
    { "code": 15, "name": "BARRENO ABOCARDADO" },
    { "code": 16, "name": "BARRENO CON REBABAS" },
    { "code": 17, "name": "BARRENO DESPLAZADO" },
    { "code": 19, "name": "BURBUJAS DE AIRE" },
    { "code": 20, "name": "BUTILO EMBARRADO" },
    { "code": 21, "name": "CAIDA" },
    { "code": 27, "name": "CLIP EQUIVOCADO" },
    { "code": 28, "name": "CLIP MAL ENSAMBLE" },
    { "code": 29, "name": "CLIP ROTO" },
    { "code": 31, "name": "CLIP SIN COLOCAR" },
    { "code": 32, "name": "CON FUGA" },
    { "code": 33, "name": "CON INTERFERENCIA" },
    { "code": 34, "name": "CON REBABA" },
    { "code": 35, "name": "CON RUIDO" },
    { "code": 41, "name": "CORTO" },
    { "code": 42, "name": "DAÑADO (A)" },
    { "code": 43, "name": "DEFORMADO (A)" },
    { "code": 49, "name": "DESPLAZADO (A)" },
    { "code": 50, "name": "DIFERENTE TONO" },
    { "code": 52, "name": "DOBLADA" },
    { "code": 53, "name": "EQUIVOCADO (A)" },
    { "code": 54, "name": "ESCORIA DE SOLDADURA" },
    { "code": 57, "name": "EXCESO DE APRIETE" },
    { "code": 62, "name": "FALLA DE DESVANECIDO" },
    { "code": 64, "name": "FALLA DE ESTAMPADO" },
    { "code": 66, "name": "FALTA" },
    { "code": 67, "name": "FALTA ABRAZADERA" },
    { "code": 69, "name": "FALTA APRIETE" },
    { "code": 72, "name": "FALTA CERA" },
    { "code": 73, "name": "FALTA CHAVETA" },
    { "code": 75, "name": "FALTA CLIP" },
    { "code": 76, "name": "FALTA COLOR" },
    { "code": 78, "name": "FALTA ENCINTAR" },
    { "code": 79, "name": "FALTA FUSIBLE" },
    { "code": 80, "name": "FALTA GOMA" },
    { "code": 82, "name": "FALTA HUESO" },
    { "code": 85, "name": "FALTA PIJA" },
    { "code": 86, "name": "FALTA PINTAR" },
    { "code": 89, "name": "FALTA SEGURO" },
    { "code": 90, "name": "FALTA SELLO" },
    { "code": 91, "name": "FALTA SELLO SOL" },
    { "code": 93, "name": "FALTA SOPORTE" },
    { "code": 94, "name": "FALTA TAPON" },
    { "code": 95, "name": "FALTA TORNILLO" },
    { "code": 97, "name": "FALTA TUERCA" },
    { "code": 100, "name": "FORZADO (A)" },
    { "code": 101, "name": "FUERA DE CLIP" },
    { "code": 107, "name": "GOMA MAL ENSAMBLADA" },
    { "code": 109, "name": "HOLGURA INCORRECTA" },
    { "code": 114, "name": "LARGO" },
    { "code": 120, "name": "MAL ENSAMBLADO" },
    { "code": 121, "name": "MAL FUNCIONAMIENTO" },
    { "code": 124, "name": "MANCHADO (A)" },
    { "code": 127, "name": "MATERIAL SOBRANTE" },
    { "code": 130, "name": "NIVEL INCORRECTO" },
    { "code": 134, "name": "NO ASIENTA" },
    { "code": 138, "name": "NO FUNCIONA" },
    { "code": 140, "name": "ONDULADO" }
  ],
  "defectos 2": [
    { "code": 149, "name": "PIJA FALTA APRIETE" },
  { "code": 150, "name": "PINTURA BRISADA" },
  { "code": 153, "name": "PINTURA CON BASURA" },
  { "code": 156, "name": "PINTURA CON FIBRA" },
  { "code": 158, "name": "PINTURA CON REPEGON" },
  { "code": 161, "name": "PINTURA DESCASCARADA" },
  { "code": 162, "name": "PINTURA EMBARRADA" },
  { "code": 163, "name": "PINTURA ESCURRIDA" },
  { "code": 164, "name": "PINTURA ESTRELLADA" },
  { "code": 166, "name": "PINTURA HERVIDA" },
  { "code": 167, "name": "PINTURA LIJADA" },
  { "code": 170, "name": "PINTURA RAYADA" },
  { "code": 171, "name": "PINTURA RESECA" },
  { "code": 175, "name": "PRENSADO" },
  { "code": 176, "name": "PRIMER EMBARRADO" },
  { "code": 177, "name": "PUNTO CON REBABA" },
  { "code": 178, "name": "PUNTO MAL COLOCADO" },
  { "code": 184, "name": "RAYADA" },
  { "code": 185, "name": "RAYAS BAJO PINTURA" },
  { "code": 188, "name": "REBABA DE SOLDADURA" },
  { "code": 191, "name": "RESANE MAL APLICADO" },
  { "code": 194, "name": "RETOQUE MAL APLICADO" },
  { "code": 197, "name": "ROTO (A)" },
  { "code": 201, "name": "RUIDO AL CERRAR" },
  { "code": 202, "name": "RUTA INCORRECTA" },
  { "code": 209, "name": "SELLO CON BURBUJA" },
  { "code": 214, "name": "SELLO MAL APLICADO" },
  { "code": 218, "name": "SIN CONECTAR" },
  { "code": 222, "name": "SUCIA (O)" },
  { "code": 223, "name": "SUELTO" },
  { "code": 225, "name": "TORCIDO" },
  { "code": 226, "name": "TORNILLO BARRIDO" },
  { "code": 227, "name": "TORNILLO DEGOLLADO" },
  { "code": 228, "name": "TORNILLO FALTA APRIETE" },
  { "code": 229, "name": "TORNILLOS EQUIVOCADOS" },
  { "code": 232, "name": "TUERCA FALTA APRIETE" },
  { "code": 233, "name": "TUERCAS TRASLAPADAS" },
  { "code": 234, "name": "URETANO EMBARRADO" },
  { "code": 242, "name": "SELLO ESTRELLADO" },
  { "code": 246, "name": "SOPORTE DAÑADO" },
  { "code": 248, "name": "SOPORTE MAL ENSAMBLE" },
  { "code": 253, "name": "TUERCAS EQUIVOCADAS" },
  { "code": 263, "name": "FUERA DE GUIA" },
  { "code": 268, "name": "ACEITE REGADO" },
  { "code": 271, "name": "ABRASIONES" },
  { "code": 275, "name": "ARNES DAÑADO/DEGOLLADO" },
  { "code": 276, "name": "BARRENO TRASLAPADO" },
  { "code": 278, "name": "BIRLO BARRIDO" },
  { "code": 281, "name": "CLIP NO ATORA" },
  { "code": 282, "name": "FUGA ANTICONGELANTE" },
  { "code": 286, "name": "CON ROCE" },
  { "code": 288, "name": "ETIQUETA DAÑADA" },
  { "code": 290, "name": "FALTA ANTICONGELANTE" },
  { "code": 291, "name": "FALTA BIRLO" },
  { "code": 293, "name": "FALTA GAS A/C" },
  { "code": 294, "name": "FALTA TAPA" },
  { "code": 295, "name": "FALTA TAPA/CUBIERTA" },
  { "code": 301, "name": "NO ASIENTA (POR TRASLAPE)" },
  { "code": 313, "name": "SOPORTE FALTA APRIETE" },
  { "code": 315, "name": "TUERCA BARRIDA" },
  { "code": 320, "name": "FALTA REMACHE" },
  { "code": 330, "name": "REMACHE MAL ENSAMBLE" },
  { "code": 332, "name": "TAPA MAL ENSAMBLE" },
  { "code": 339, "name": "BIRLO DAÑADO/DOBLADO" },
  { "code": 341, "name": "BIRLO DESPLAZADO" },
  { "code": 357, "name": "ARNES FALTA CONECTAR" }
  ]
};
